[tools]
"aqua:hugo-extended" = "0.142.0"
node = "24"

[tasks]
start = "./scripts/manage_hugo.sh start"
restart = "./scripts/manage_hugo.sh restart"
stop = "./scripts/manage_hugo.sh stop"
status = "./scripts/manage_hugo.sh status"
